name: Deploy to Production
on:
  workflow_dispatch:

env:
  PROJECT_ID: talk-to-your-records
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/talk-to-your-records/icliniq-search
  AI_CHAT_API_KEY: ${{ secrets.AI_CHAT_API_KEY }}

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_TALK_TO_YOUR_RECORDS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker Authentication
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get latest dev image tag
        id: get-latest-tag
        run: |
          IMAGE_TAG=$(gcloud run services describe icliniq-search-dev \
            --region=${{ env.REGION }} \
            --format="json" | jq -r '.spec.template.spec.containers[0].image')
          echo "Latest Image Tag: $IMAGE_TAG"
          echo "::set-output name=image-tag::$IMAGE_TAG"

      - name: Extract commit hash
        id: extract-hash
        run: |
          COMMIT_HASH=$(echo "${{ steps.get-latest-tag.outputs.image-tag }}" | cut -d':' -f2)
          echo "::set-output name=commit-sha::$COMMIT_HASH"

      - name: Deploy to Production
        run: |
          gcloud run deploy icliniq-search \
            --image ${{ env.GAR_LOCATION }}/icliniq-search:${{ steps.extract-hash.outputs.commit-sha }} \
            --port 8090 \
            --memory 2Gi \
            --region ${{ env.REGION }} \
            --platform managed \
            --set-env-vars AI_CHAT_API_KEY="${{ env.AI_CHAT_API_KEY }}"
