on:
  push:
    branches:
      - main
    paths:
      - "dev/**"
      - ".github/workflows/dev-deploy.yml"

env:
  PROJECT_ID: talk-to-your-records
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/talk-to-your-records/icliniq-search-dev

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: dev/
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Store Service Account Credentials in JSON File
            env:
              GCP_SA_TALK_TO_YOUR_RECORDS: ${{ secrets.GCP_TALK_TO_YOUR_RECORDS }}
            run: |
              echo "$GCP_SA_TALK_TO_YOUR_RECORDS" > talk-to-your-records-1dd5074904a9.json
      
          - id: 'auth'
            name: 'Authenticate to Google Cloud'
            uses: 'google-github-actions/auth@v1'
            with:
                credentials_json: '${{ secrets.GCP_TALK_TO_YOUR_RECORDS }}'

          - name: Get the commit SHA
            id: vars
            run: echo ::set-output name=sha::$(git rev-parse HEAD)

          - name: "Set up google cloud CLI"
            uses: "google-github-actions/setup-gcloud@v1"
    
          - name: "Docker auth"
            run: |-
              gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

          - name: Build image
            run: |
              docker build . --file ./dev.Dockerfile --tag ${{ env.GAR_LOCATION }}/icliniq-search:${{ steps.vars.outputs.sha }}

          - name: Push image
            run: docker push ${{ env.GAR_LOCATION }}/icliniq-search:${{ steps.vars.outputs.sha }}

          - name: Deploy to Cloud Run
            run: |
                gcloud run deploy icliniq-search-dev \
                --image ${{ env.GAR_LOCATION }}/icliniq-search:${{ steps.vars.outputs.sha }} \
                --port 8090 \
                --memory 2Gi \
                --region ${{ env.REGION }} \
                --platform managed